services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: CarRentApp

  django:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      POSTGRES_HOST: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: CarRentApp
    ports:
      - "8001:8000"