name: Django CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
      - name: Run PEP8
        continue-on-error: true
        run: |
          pycodestyle --exclude ".venv,**/migrations/" --max-line-length 120 --format '::warning file=%(path)s,line=%(row)d,col=%(col)d::%(code)s %(text)s'  .
  push:
    runs-on: ubuntu-latest
    if: github.repository == 'main'
    needs:
      - test
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: gaborka98/django-test:latest