name: Django CD

on:
  push:
    branches: [ "main" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: webiny/action-conventional-commits@v1.3.0
      - name: Parse version
        run: |
          version=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=\()\d+\.\d+\.\d+(?=\))')
          echo $version
          
          echo "VERSION=$version" >> $GITHUB_ENV


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: gaborka98/django-test:${{ env.VERSION }}